# Site settings
author: Kevin O'Brien
title: Coding with Kevin
header-img: img/home-bg.png
email: kpobrien@buffalo.edu
copyright_name: Kevin O'Brien
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey as I learn to code!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpobrien4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
