# Site settings
author: Kevin OBrien
title: Kevin Blog
header-img: img/home-bg.png
email: kpobrien@buffalo.edu
copyright_name: Kevin OBrien
description: > # this means to ignore newlines until "baseurl:"
  A coding blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpobrien4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
